services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8006:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://family-stock:password@db:5432/family-stock
      NEXTAUTH_URL: https://stocks.shieru-lab.com
      HOST: "0.0.0.0"
      PORT: 3000
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: family-stock
      POSTGRES_PASSWORD: password
      POSTGRES_DB: family-stock
      POSTGRES_PORT: 5432
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
